name: FreeBSD and (eventually) Solaris

on: [push]

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: A job to run test FreeBSD
    steps:
    - uses: actions/checkout@v2
    - name: FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.1.4
      with:
        usesh: true
        prepare: pkg install -y perl5 curl gmake
        run: |
          curl -L https://cpanmin.us | perl - App::cpanminus
          cpanm -v -n --installdeps https://github.com/sanko/Alien-libsdl2/tarball/main
          cpanm -v --test-only https://github.com/sanko/Alien-libsdl2/tarball/main
# Solaris is broken
#  testsolaris:
#    runs-on: macos-latest
#    name: A job to run test Solaris
#    steps:
#    - uses: actions/checkout@v2
#    - name: Solaris
#      id: test
#      uses: vmactions/solaris-vm@v0.0.3
#      with:
#        run: |
#          perl -v
#          curl -L https://cpanmin.us | perl - App::cpanminus
#          cpanm -v -n --installdeps https://github.com/sanko/Alien-libsdl2/tarball/main
#          cpanm -v --test-only https://github.com/sanko/Alien-libsdl2/tarball/main