name: FreeBSD

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'

jobs:
  testfreebsd:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        perl: [ '5-5.32.1_1', '5-devel-5.35.1.50', '5.30-5.30.3_1', '5.34-5.34.0' ]
    name: Perl ${{matrix.perl}}
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        run: |
          ls -lah
          whoami
          env
          freebsd-version
          pkg search perl5
          pkg install --yes --recursive perl${{ matrix.perl }}
          pkg install --yes --recursive curl
          curl -L https://cpanmin.us | perl - App::cpanminus
          cpanm -v --test-only .
    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1.11.0
      with:
          perl-version: ${{ matrix.perl }}

    - name: perl -V
      run: perl -V